name: Home-Server Deployment
on:
  push:
    branches: [master]
jobs:
  server-deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: ./
        with:
          server: www.bao-home-server.site
          username: ftpUserConnection
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /ftpUserConnection/AdvantageWebServer/advanced_web_programing
