name: Home-Server Deployment
on:
  push:
    branches: [home-server-deployment]
jobs:
  deploy:
    name: Deloy
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@main
      - name: package install
        working-directory: ./be
        run: npm ci
      - name: docker info
        working-directory: ./be
        run: docker info
      - name: docker down
        working-directory: ./be
        run: docker-compose -f "docker-compose.yml" down -v
      - name: docker up
        working-directory: ./be
        run: docker-compose up -d
