name: Home-Server Deployment
on:
  push:
    branches: [home-server-deployment]
jobs:
  deploy:
    name: Deloy
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@main
      - name: Docker down
        run: docker-compose down -v
      - name: Docker up
        run: docker-compose up -d
        
