name: Home-Server Deployment
on:
  push:
    branches: [home-server-deployment]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout repository
        uses: actions/checkout@home-server-deployment
      - name: package install
        run: npm ci
        working-directory: be

